// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE38mIJRYg1xdXHyxdsphnVyXTxlkO6DM',
    appId: '1:185732800857:web:e263841f42d166fee46c48',
    messagingSenderId: '185732800857',
    projectId: 'desperdiciocero-f3a23',
    authDomain: 'desperdiciocero-f3a23.firebaseapp.com',
    storageBucket: 'desperdiciocero-f3a23.appspot.com',
    measurementId: 'G-JB8C31JJB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9n1QMXBmleos3Zt0Dgoln2FESwm8iTKM',
    appId: '1:185732800857:android:5ccd38df9e3b209de46c48',
    messagingSenderId: '185732800857',
    projectId: 'desperdiciocero-f3a23',
    storageBucket: 'desperdiciocero-f3a23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcD532rtXnAXLiYRclEPvRz7GaPnOvGY',
    appId: '1:185732800857:ios:eae7426dbf80405de46c48',
    messagingSenderId: '185732800857',
    projectId: 'desperdiciocero-f3a23',
    storageBucket: 'desperdiciocero-f3a23.appspot.com',
    iosBundleId: 'com.example.desperdicioCero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcD532rtXnAXLiYRclEPvRz7GaPnOvGY',
    appId: '1:185732800857:ios:eae7426dbf80405de46c48',
    messagingSenderId: '185732800857',
    projectId: 'desperdiciocero-f3a23',
    storageBucket: 'desperdiciocero-f3a23.appspot.com',
    iosBundleId: 'com.example.desperdicioCero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE38mIJRYg1xdXHyxdsphnVyXTxlkO6DM',
    appId: '1:185732800857:web:2955dd34b2ce16dde46c48',
    messagingSenderId: '185732800857',
    projectId: 'desperdiciocero-f3a23',
    authDomain: 'desperdiciocero-f3a23.firebaseapp.com',
    storageBucket: 'desperdiciocero-f3a23.appspot.com',
    measurementId: 'G-HW2YJ27SQB',
  );
}
