/*
  Este archivo contiene los datos de los productos que se mostrarán en la aplicación.
  Cada producto tiene un nombre y una categoría.
  La categoría se utiliza para mostrar los productos en la pantalla de inicio de la aplicación.
*/
const Map<String, String> productos = {
  // Productos de la categoría "Frutas"
  "Manzanas": "Frutas",
  "Plátanos": "Frutas",
  "Naranjas": "Frutas",
  "Peras": "Frutas",
  "Uvas": "Frutas",
  "Fresas": "Frutas",
  "Kiwis": "Frutas",
  "Melocotones": "Frutas",
  "Piña": "Frutas",
  "Mangos": "Frutas",
  "Cerezas": "Frutas",
  "Limones": "Frutas",
  "Cocos": "Frutas",
  "Pomelos": "Frutas",
  "Mandarinas": "Frutas",
  "Ciruelas": "Frutas",
  "Albaricoques": "Frutas",
  "Higos": "Frutas",
  "Caquis": "Frutas",
  "Papayas": "Frutas",
  "Granadas": "Frutas",
  "Chirimoyas": "Frutas",
  "Nísperos": "Frutas",
  "Aguacates": "Frutas",
  "Guayabas": "Frutas",
  "Moras": "Frutas",
  "Frambuesas": "Frutas",
  "Arándanos": "Frutas",
  "Grosellas": "Frutas",
  "Manzana": "Frutas",
  "Plátano": "Frutas",
  "Naranja": "Frutas",
  "Pera": "Frutas",
  "Uva": "Frutas",
  "Fresa": "Frutas",
  "Kiwi": "Frutas",
  "Melocotón": "Frutas",
  "Mango": "Frutas",
  "Cereza": "Frutas",
  "Limón": "Frutas",
  "Coco": "Frutas",
  "Pomelo": "Frutas",
  "Mandarina": "Frutas",
  "Ciruela": "Frutas",
  "Albaricoque": "Frutas",
  "Higo": "Frutas",
  "Caqui": "Frutas",
  "Papaya": "Frutas",
  "Granada": "Frutas",
  "Chirimoya": "Frutas",
  "Níspero": "Frutas",
  "Aguacate": "Frutas",
  "Guayaba": "Frutas",
  "Mora": "Frutas",
  "Frambuesa": "Frutas",
  "Arándano": "Frutas",
  "Grosella": "Frutas",

  // Productos de la categoría "Frutos_secos"
  "Castaña": "Frutos_secos",
  "Avellana": "Frutos_secos",
  "Nuez": "Frutos_secos",
  "Pistacho": "Frutos_secos",
  "Almendra": "Frutos_secos",
  "Anacardo": "Frutos_secos",
  "Cacahuete": "Frutos_secos",
  "Piñón": "Frutos_secos",
  "Castañas": "Frutos_secos",
  "Avellanas": "Frutos_secos",
  "Nueces": "Frutos_secos",
  "Pistachos": "Frutos_secos",
  "Almendras": "Frutos_secos",
  "Anacardos": "Frutos_secos",
  "Cacahuetes": "Frutos_secos",
  "Piñónes": "Frutos_secos",

  // Productos de la categoría "Verduras"
  "Zanahoria": "Verduras",
  "Pimiento": "Verduras",
  "Pimiento Rojo": "Verduras",
  "Pimiento Verde": "Verduras",
  "Pimiento Amarillo": "Verduras",
  "Pimiento Choricero": "Verduras",
  "Pimiento del Piquillo": "Verduras",
  "Tomate": "Verduras",
  "Lechuga": "Verduras",
  "Espinaca": "Verduras",
  "Coliflor": "Verduras",
  "Brócoli": "Verduras",
  "Calabacín": "Verduras",
  "Berenjena": "Verduras",
  "Pepino": "Verduras",
  "Patata": "Verduras",
  "Cebolla": "Verduras",
  "Ajo": "Verduras",
  "Puerro": "Verduras",
  "Calabaza": "Verduras",
  "Judía": "Verduras",
  "Guisante": "Verduras",
  "Alcachofa": "Verduras",
  "Champiñón": "Verduras",
  "Seta": "Verduras",
  "Rábano": "Verduras",
  "Apio": "Verduras",
  "Espárrago": "Verduras",
  "Acelga": "Verduras",
  "Boniato": "Verduras",
  "Chirivía": "Verduras",
  "Nabo": "Verduras",
  "Rúcula": "Verduras",
  "Canónigo": "Verduras",
  "Endibia": "Verduras",
  "Escarola": "Verduras",
  "Lombarda": "Verduras",
  "Maíz": "Verduras",
  "Bambú": "Verduras",
  "Cebollino": "Verduras",
  "Col": "Verduras",
  "Col rizada": "Verduras",
  "Zanahorias": "Verduras",
  "Pimientos": "Verduras",
  "Pimientos Rojos": "Verduras",
  "Pimientos Verdes": "Verduras",
  "Pimientos Amarillos": "Verduras",
  "Pimientos Choricero": "Verduras",
  "Pimientos del Piquillo": "Verduras",
  "Tomates": "Verduras",
  "Espinacas": "Verduras",
  "Calabacínes": "Verduras",
  "Berenjenas": "Verduras",
  "Pepinos": "Verduras",
  "Patatas": "Verduras",
  "Cebollas": "Verduras",
  "Ajos": "Verduras",
  "Puerros": "Verduras",
  "Calabazas": "Verduras",
  "Judías": "Verduras",
  "Alcachofas": "Verduras",
  "Champiñónes": "Verduras",
  "Setas": "Verduras",
  "Rábanos": "Verduras",
  "Apios": "Verduras",
  "Espárragos": "Verduras",
  "Acelgas": "Verduras",
  "Boniatos": "Verduras",
  "Chirivías": "Verduras",
  "Nabos": "Verduras",
  "Canónigos": "Verduras",
  "Coles": "Verduras",

  // Productos de la categoría "Legumbres"
  "Lentejas": "Legumbres",
  "Garbanzos": "Legumbres",
  "Judías verdes": "Legumbres",
  "Alubias": "Legumbres",
  "Frijoles": "Legumbres",
  "Habichuelas": "Legumbres",
  "Soja": "Legumbres",
  "Guisantes": "Legumbres",
  "Habas": "Legumbres",
  "Alubias Blancas": "Legumbres",
  "Alubias Negras": "Legumbres",
  "Alubias Rojas": "Legumbres",
  "Alubias Pintas": "Legumbres",
  "Alubias Verdes": "Legumbres",

  // Productos de la categoría "Pescado"
  "Salmón": "Pescado",
  "Atún": "Pescado",
  "Bacalao": "Pescado",
  "Lomos de Bacalao": "Pescado",
  "Merluza": "Pescado",
  "Dorada": "Pescado",
  "Lubina": "Pescado",
  "Sardina": "Pescado",
  "Boquerón": "Pescado",
  "Anchoa": "Pescado",
  "Pulpo": "Pescado",
  "Calamar": "Pescado",
  "Calamares": "Pescado",
  "Sepia": "Pescado",
  "Gambas": "Pescado",
  "Gamba": "Pescado",
  "Langostinos": "Pescado",
  "Cigalas": "Pescado",
  "Carabineros": "Pescado",
  "Mejillones": "Pescado",
  "Almejas": "Pescado",
  "Berberechos": "Pescado",
  "Ostras": "Pescado",
  "Vieiras": "Pescado",
  "Cangrejo": "Pescado",
  "Centollo": "Pescado",
  "Bogavante": "Pescado",
  "Langosta": "Pescado",
  "Camarón": "Pescado",
  "Bonito": "Pescado",
  "Salmón Ahumado": "Pescado",
  "Atún en Conserva": "Pescado",

  // Productos de la categoría "Carne"
  "Ternera": "Carne",
  "Cerdo": "Carne",
  "Pollo": "Carne",
  "Pavo": "Carne",
  "Cordero": "Carne",
  "Conejo": "Carne",
  "Pato": "Carne",
  "Codorniz": "Carne",
  "Beicon": "Carne",
  "Chorizo": "Carne",
  "Salchichas": "Carne",
  "Filete de Ternera": "Carne",
  "Filete de Cerdo": "Carne",
  "Filete de Pollo": "Carne",
  "Filete de Pavo": "Carne",
  "Filete de Cordero": "Carne",
  "Morcilla": "Carne",
  "Butifarra": "Carne",
  "Hamburguesa": "Carne",
  "Salchicha": "Carne",
  "Salchichón": "Carne",
  "Chuleta de Ternera": "Carne",
  "Chuleta de Cerdo": "Carne",
  "Chuleta de Pollo": "Carne",
  "Chuleta de Pavo": "Carne",
  "Chuleta de Cordero": "Carne",
  "Morcillo": "Carne",
  "Costilla de Cerdo": "Carne",
  "Costilla de Ternera": "Carne",
  "Costilla de Cordero": "Carne",
  "Costilla de Pavo": "Carne",
  "Costilla de Pollo": "Carne",
  "Tocino": "Carne",
  "Panceta": "Carne",
  "Jamón": "Carne",
  "Jamón Serrano": "Carne",
  "Jamón Ibérico": "Carne",
  "Jamón Cocido": "Carne",
  "Jamón York": "Carne",
  "Gallina": "Carne",
  "Pechuga de Pollo": "Carne",
  "Pechuga de Pavo": "Carne",
  "Pechuga de Ternera": "Carne",
  "Pechuga de Cerdo": "Carne",
  "Muslo de Pollo": "Carne",
  "Muslo de Pavo": "Carne",
  "Muslo de Ternera": "Carne",
  "Muslo de Cerdo": "Carne",
  "Alitas de Pollo": "Carne",

  // Productos de la categoría "Lácteos"
  "Leche": "Lacteos",
  "Leche entera": "Lacteos",
  "Leche semidesnatada": "Lacteos",
  "Leche desnatada": "Lacteos",
  "Queso": "Lacteos",
  "Yogur": "Lacteos",
  "Mantequilla": "Lacteos",
  "Nata": "Lacteos",
  "Huevos": "Lacteos",
  "Caldo de Pollo": "Lacteos",
  "Caldo de Verduras": "Lacteos",
  "Caldo de Carne": "Lacteos",
  "Caldo de Pescado": "Lacteos",
  "Aceite de Oliva": "Lacteos",
  "Aceite de Oliva Virgen Extra": "Lacteos",
  "Aceite de Girasol": "Lacteos",
  "Aceite de Palma": "Lacteos",
  "Leche de Coco": "Lacteos",
  "Mayonesa": "Lacteos",
  "Mahonesa": "Lacteos",
  "Ketchup": "Lacteos",
  "Mostaza": "Lacteos",
  "Mermerlada de fresa": "Lacteos",
  "Mermelada de melocotón": "Lacteos",
  "Mermelada de naranja": "Lacteos",
  "Mermelada de frambuesa": "Lacteos",
  "Mermelada de arándanos": "Lacteos",
  "Mermelada de mora": "Lacteos",
  "Mermelada de ciruela": "Lacteos",
  "Mermelada de albaricoque": "Lacteos",
  "Mermelada de higo": "Lacteos",
  "Salsa de tomate": "Lacteos",


  // Productos de la categoría "Cereales"
  "Arroz": "Cereales",
  "Harina de Trigo": "Cereales",
  "Avena": "Cereales",
  "Harina de Maíz": "Cereales",
  "Cebada": "Cereales",
  "Centeno": "Cereales",
  "Quinoa": "Cereales",
  "Sémola": "Cereales",
  "Macarrones": "Cereales",
  "Espaguetis": "Cereales",
  "Pan": "Cereales",
  "Galletas": "Cereales",
  "Galleta": "Cereales",
  "Cereales": "Cereales",

  // Productos de la categoría "Especias"
  "Sal": "Especias",
  "Sal Gruesa": "Especias",
  "Azúcar": "Especias",
  "Azafrán": "Especias",
  "Canela": "Especias",
  "Clavo": "Especias",
  "Comino": "Especias",
  "Curry": "Especias",
  "Jengibre": "Especias",
  "Nuez Moscada": "Especias",
  "Pimienta": "Especias",
  "Pimentón": "Especias",
  "Romero": "Especias",
  "Tomillo": "Especias",
  "Vainilla": "Especias",
  "Orégano": "Especias",
  "Albahaca": "Especias",
  "Laurel": "Especias",
  "Perejil": "Especias",
  "Cilantro": "Especias",
  "Eneldo": "Especias",
  "Hinojo": "Especias",
  "Salvia": "Especias",
  "Estragón": "Especias",
  "Cúrcuma": "Especias",
  "Cardamomo": "Especias",
  "Anís": "Especias",
  "Pimienta Negra": "Especias",
  "Cayena": "Especias",
  "Pimentón Picante": "Especias",
  "Pimentón Dulce": "Especias",
  "Pimienta Blanca": "Especias",
  "Guindilla": "Especias",
};